### ISSUE TITLE
Broken Stacker News referral link on proxnut.com

### ISSUE THREAD

**Issue by ekzyis** [gandlafbtc/proxnut#3]
Hey, I have noticed that you have this link to Stacker News on [proxnut.com](https://proxnut.com): 

https://stacker.news/r/mo/search?q=PROXNUT&what=posts

Thanks for the link! We like to see our site mentioned in the wild.

However, this link does redirect to the frontpage and not to all posts which mention proxnut. I am actually not sure if that link used to work since there were [no updates to our referral middleware since inception afaict](https://github.com/stackernews/stacker.news/blob/master/middleware.js) (/cc @huumn).

The correct link would be this:

```diff
- https://stacker.news/r/mo/search?q=PROXNUT&what=posts
+ https://stacker.news/search/r/mo?q=PROXNUT&what=posts
```
I wanted to create a PR o fix this but I haven't found the link in your code.

I think this repository only contains the code for the wallet, not for [proxnut.com](https://proxnut.com/)?

**Comment by huumn** [comment]
https://stacker.news/search/r/mo?q=PROXNUT&what=posts

The above link works for me

**Comment by gandlafbtc** [comment]
yes! the website is in a separate repo

https://github.com/gandlafbtc/proxnut-website

please open PR there.

Thanks for the fix!
